### ISSUE TITLE
Since FF v44.0: Not working anymore

### ISSUE THREAD

**Issue by AtTheGates** [hjgwmvya/redirect-control#1]
Hello,

first thank you very much for your nice and important security extension.

Sadly since **FF v44.0** the extension isn't working anymore. So it doesn't "jump in" if there are any redirections. With **FF v43.0.x** it's still working fine.

Tested in new/ clean profiles with **Redirect Control v0.0.7**.

Thank you in advance. :-)

**Comment by AtTheGates** [comment]
For the case you are not aware of this: Could it have to do with this? [**Breaking changes in let and const in Firefox Nightly 44**](https://blog.mozilla.org/addons/2015/10/14/breaking-changes-let-const-firefox-nightly-44)

Greet

**Comment by Botlover** [comment]
@hjgwmvya Just to add more to this, I have also tested this and can confirm. Works fine with FF, Waterfox and Cyberfox 43.0.x but not with any 44.0.x. 

Would really like to see this working again. 

Thanks!

**Comment by AtTheGates** [comment]
I saw the new **version 0.0.8** on [**AMO**](https://addons.mozilla.org/firefox/addon/redirect-control/versions/). Now it works with **FF v44** again. Thank you very much. :-)

I think, I can close this issue, right?

**Comment by hjgwmvya** [comment]
Thank you for the link :) I didn't noticed it before.
