### ISSUE TITLE
Make redirect-control compatible with Firefox 50

### ISSUE THREAD

**Issue by kenkon2** [hjgwmvya/redirect-control#11]
I don't know what has changed in Firefox 50 but redirect-control has stopped working. Although redirect-control isn't disabled by Firefox in Add-ons Manager, it doesn't block any redirects (meta-refresh, window.location, etc.) anymore and its options are gone too.

Please update this wonderful extension to make it work in Firefox 50!

Windows 10 x64
Firefox 50.0 64-bit
Redirect Control 0.1.2
(plus several other extensions)

**Comment by hjgwmvya** [comment]
Thanks for reporting the problem.

There was a problem during the startup of the addon in Firefox 50. I have uploaded a new version with a bugfix for this problem.

**Comment by githtz** [comment]
Thanks for fixing this issue that quickly! Version 0.1.3 is available at https://addons.mozilla.org/de/firefox/addon/redirect-control/ and working again.
