### ISSUE TITLE
[questions and feature requests]

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [hjgwmvya/redirect-control#2]
i really like your addon and the idea behind it, but i have a few questions and requests if you dont mind

1.
```
Following requests are allowed by default:
    If origin and destination of the request have the same base domain (e.g. abc.domain.tld -> xyz.domain.tld)
    Requests triggered by a link click
    Requests matching user-defined rules
```
i was wondering if the first 2 requests mentioned above could be made optionally disallowed by default, or at least the first one

2. do the rules support more than just `* = any domain`? for e.g. will `*.domain.com` match www.domain.com and sub.www.domain.com? if not, maybe consider adding more wildcard support? or even [optional] regex support

3. i think it would be a lot nicer if there were a way to batch add/remove rules. maybe have an option to allow manual editing of the entire list? so one could copy/paste rules or remove rules more easily. or just replace the entire current layout and have it displayed in a single text box as a sorted list and have a Save and Cancel button. and the current input boxes at the top for quick adding? im not sure

let me know what you think of the ideas :)

**Comment by hjgwmvya** [comment]
Thank you for your ideas.

In version 0.1.0 i added some new optiones for rules (optional handle subdomains, wildcards, regular expressions).

To manage a larger list of rules you can now export the rules, modify the file, and import it again. I hope it helps you a little bit.

**Comment by berrythesoftwarecodeprogrammar** [comment]
oh thank you :)

it seems 0.1.0 isnt on the mozilla addons page, only 0.0.7

**Comment by berrythesoftwarecodeprogrammar** [comment]
nevermind i found it here https://addons.mozilla.org/en-US/firefox/addon/redirect-control/versions/
