### ISSUE TITLE
Ignore subdomains blocks viewing page source

### ISSUE THREAD

**Issue by TeroLe** [hjgwmvya/redirect-control#6]
When the "Ignore subdomains" option is selected and you try to view a page's source with either Ctrl+U or from the right-click menu you only get a blank page. When the option is deselected you get a notification to allow a redirect and if you allow it the source is displayed.

Expected behavior is to have the page source displayed without a redirect notification.

**Comment by hjgwmvya** [comment]
Thanks for the bug report.

I have fixed it in version 0.1.2. Now you shouldn't get a request anymore for the source view page.

**Comment by TeroLe** [comment]
Thanks for the fix.
